site_name: Repositório de Estudos

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro


nav:
  - Português:
    - Fonologia: portugues/fonologia.md
    - Divisão Silábica: portugues/div_silabica.md
    - Acentuação: portugues/acentuacao.md
    - Morfologia: portugues/morfologia.md
  - Matemática:
    - Frações e Equações: matematica/fracao_equacao.md
    - Regras das Quatro Operações: matematica/adicao_subtracao.md
    - Potenciação: matematica/potenciação.md

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - admonition
  - pymdownx.arithmatex:
        generic: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
